WITH RECURSIVE hours AS (
  SELECT 0 AS HOUR
  UNION ALL
  SELECT HOUR + 1 FROM hours WHERE HOUR < 23
)

SELECT 
  h.HOUR,
  IFNULL(o.COUNT, 0) AS COUNT
FROM hours h
LEFT JOIN (
  SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
  FROM ANIMAL_OUTS
  GROUP BY HOUR(DATETIME)
) o ON o.HOUR = h.HOUR
ORDER BY h.HOUR;