SELECT T.ID, T.EMAIL, T.FIRST_NAME, T.LAST_NAME
FROM (
    SELECT D.ID, D.FIRST_NAME, D.LAST_NAME, D.EMAIL, GROUP_CONCAT(S.CATEGORY) AS CATEGORES, GROUP_CONCAT(S.NAME) AS NAMES 
    FROM DEVELOPERS AS D 
    JOIN SKILLCODES AS S ON (S.CODE & D.SKILL_CODE) = S.CODE
    GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
) AS T
WHERE T.CATEGORES LIKE '%Front End%'