WITH SCORES AS (
    SELECT he.EMP_NO, he.EMP_NAME, he.SAL, AVG(hg.SCORE) AS SCORE
    FROM HR_EMPLOYEES AS he
    LEFT JOIN HR_GRADE AS hg ON he.EMP_NO = hg.EMP_NO
    GROUP BY he.EMP_NO, he.EMP_NAME, hE.SAL
)

SELECT 
S.EMP_NO, 
S.EMP_NAME,
CASE WHEN S.SCORE >= 96 THEN 'S'
     WHEN S.SCORE >= 90 THEN 'A'
     WHEN S.SCORE >= 80 THEN 'B'
ELSE 'C' 
END AS GRADE, 
S.SAL * CASE 
    WHEN S.SCORE >= 96 THEN 0.20
    WHEN S.SCORE >= 90 THEN 0.15
    WHEN S.SCORE >= 80 THEN 0.10
    ELSE 0
END AS BONUS
FROM SCORES AS S
ORDER BY S.EMP_NO
