SELECT
CASE 
    WHEN (TMP.CATEGORES LIKE '%Front End%' AND TMP.NAMES LIKE '%Python%') THEN 'A'
    WHEN TMP.NAMES LIKE '%C#%' THEN 'B'
    WHEN TMP.CATEGORES LIKE '%Front End%' THEN 'C'
END AS GRADE, TMP.ID, TMP.EMAIL  
FROM (
    SELECT D.ID, D.EMAIL, GROUP_CONCAT(S.CATEGORY) AS CATEGORES, GROUP_CONCAT(S.NAME) AS NAMES
    FROM DEVELOPERS AS D
    JOIN SKILLCODES AS S ON (S.CODE & D.SKILL_CODE) = S.CODE
    GROUP BY D.ID, D.EMAIL
) AS TMP
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;

